version: '3.8'

services:
  event_service:
    build: ./docker/
    container_name: event_service
    command: /home/app/docker/start-app.sh
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/app
      - bundle:/bundle
    networks:
      - event-service-network
    links:
      - redis
      - mongo1
      - mongo2
      - mongo3

  redis:
    image: 'bitnami/redis:latest'
    ports:
      - 63798:6379
    environment:
        - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - event-service-network

  mongo1:
    container_name: mongo1
    image: mongo:4.4
    volumes:
      - mongo1:/data/db
      - ./docker/mongo/rs-init.sh:/scripts/rs-init.sh
    networks:
      - event-service-network
    ports:
      - 27021:27017
    links:
      - mongo2
      - mongo3
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
  mongo2:
    container_name: mongo2
    image: mongo:4.4
    volumes:
      - mongo2:/data/db
    networks:
      - event-service-network
    ports:
      - 27022:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
  mongo3:
    container_name: mongo3
    image: mongo:4.4
    volumes:
      - mongo3:/data/db
    networks:
      - event-service-network
    ports:
      - 27023:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
networks:
  event-service-network:
    driver: bridge
volumes:
  mongo1:
  mongo2:
  mongo3:
  bundle: