subgraphs:
  event_service:
    routing_url: http://docker.for.mac.localhost:3000/graphql
    schema:
      subgraph_url: http://docker.for.mac.localhost:3000/graphql
  person_service:
    routing_url: http://docker.for.mac.localhost:3001/graphql
    schema:
      subgraph_url: http://docker.for.mac.localhost:3001/graphql