version: '3.8'
services:
  person_service:
    build: ./docker/
    container_name: person_service
    command: /home/app/docker/start-app.sh
    ports:
      - "3001:3000"
    volumes:
      - ./:/home/app
      - bundle:/usr/local/bundle
    networks:
      - person-service-network
    links:
      - postgres

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '54321:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - person-service-network

networks:
  person-service-network:
    driver: bridge
volumes:
  db:
  bundle: